version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME}/frontend-cdn-user:latest
    container_name: cdn-user-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ${DOCKER_USERNAME}/cdn-user-service:latest
    container_name: cdn-user-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cdn_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: cdn-mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cdn_db
    ports:
      - "3306:3306"
    volumes:
      - ../volumes/mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: cdn-redis-local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../volumes/redis_data:/data

volumes:
  mysql_data:
  redis_data: